version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: model_api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/app/models
    networks:
      - model_network

  app:
    build:
      context: ./app
    container_name: model_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - model_network

networks:
  model_network:
    driver: bridge
